/****** Object:  StoredProcedure [dbo].[sp_MSins_dboFP_FNCL_PROD_GRP]    Script Date: 2/20/2020 3:18:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_MSins_dboFP_FNCL_PROD_GRP]
    @FNCL_PROD_GRP_ID INT,
    @SHRT_NME VARCHAR(100),
    @LONG_NME VARCHAR(100),
    @FINC_TYPE_KEY VARCHAR(25),
    @INSR_DTE DATETIME,
    @UPDT_DTE DATETIME,
    @EXEC_DTE DATETIME,
    @FLAG CHAR(1)
AS

BEGIN
    DECLARE @COMPANYID INT
    SET @COMPANYID = 2

    IF (@FLAG = 'I')
		BEGIN TRY
			IF NOT EXISTS(SELECT * FROM FINANCIALGROUP WHERE FINANCIALGROUPID = @FNCL_PROD_GRP_ID AND COMPANYID = @COMPANYID)
				BEGIN	
					INSERT INTO [DBO].[FINANCIALGROUP](
						FINANCIALGROUPID,
						COMPANYID,
						GROUPNAME,
						GROUPFULLNAME,
						CREATIONDATE
					) VALUES (
					@FNCL_PROD_GRP_ID,
					@COMPANYID,
					@SHRT_NME,
					@LONG_NME,
					@INSR_DTE
					) 
				END
		END TRY
		BEGIN CATCH
			SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;
		END CATCH;
END  
GO