SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_MSupd_dboLKUP_MAIN]
		@LKUP_MAIN_ID INT = NULL,
		@NME NVARCHAR(200) = NULL,
		@LKUP_TYPE CHAR(1) = NULL,
		@INSR_DTE DATETIME = NULL,
		@UPDT_DTE DATETIME = NULL,
		@EXEC_DTE DATETIME = NULL,
		@FLAG CHAR(1) = NULL,
		@PKC1 INT = NULL,
		@BITMAP BINARY(1)
AS
BEGIN 

	DECLARE @PRIMARYKEY_TEXT NVARCHAR(100) = ''
	DECLARE @COMPANYID SMALLINT = 1

	IF (@FLAG = 'D')
		BEGIN TRY
			IF EXISTS(SELECT * FROM LOOKUPMAIN WHERE LOOKUPMAINID = @PKC1)
				DELETE [DBO].LOOKUPMAIN WHERE LOOKUPMAINID = @PKC1
		END TRY
		BEGIN CATCH
			SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;
		END CATCH
	ELSE
		BEGIN
			BEGIN TRY
				IF EXISTS(SELECT * FROM LOOKUPMAIN WHERE LOOKUPMAINID = @PKC1)
					IF (SUBSTRING(@BITMAP,1,1) & 1 = 1)
						BEGIN 
							UPDATE [DBO].LOOKUPMAIN SET
								LOOKUPMAINID = CASE SUBSTRING(@BITMAP,1,1) & 1 WHEN 1 THEN @LKUP_MAIN_ID ELSE LOOKUPMAINID END,
								NARRATION = CASE SUBSTRING(@BITMAP,1,1) & 2 WHEN 2 THEN @NME ELSE NARRATION END,
								LOOKUPTYPE = CASE SUBSTRING(@BITMAP,1,1) & 4 WHEN 4 THEN @LKUP_TYPE ELSE LOOKUPTYPE END
							WHERE LOOKUPMAINID = @PKC1
							IF @@ROWCOUNT = 0
								IF @@MICROSOFTVERSION>0X07320000
									BEGIN
										IF EXISTS (SELECT * FROM SYS.ALL_PARAMETERS WHERE OBJECT_ID = OBJECT_ID('SP_MSREPLRAISERROR') AND [NAME] = '@PARAM3')
										BEGIN
				
											SET @PRIMARYKEY_TEXT = @PRIMARYKEY_TEXT + '[SYS_USR_ID] = ' + CONVERT(NVARCHAR(100),@PKC1,1)
											EXEC SP_MSREPLRAISERROR @ERRORID=20598, @PARAM1=N'[DBO].[UMS_SYS_USR]', @PARAM2=@PRIMARYKEY_TEXT, @PARAM3=13233 
										END
										ELSE
											EXEC SP_MSREPLRAISERROR @ERRORID=20598
									END
						END  
					ELSE
						BEGIN 
							UPDATE [DBO].LOOKUPMAIN SET
								NARRATION = CASE SUBSTRING(@BITMAP,1,1) & 2 WHEN 2 THEN @NME ELSE NARRATION END,
								LOOKUPTYPE = CASE SUBSTRING(@BITMAP,1,1) & 4 WHEN 4 THEN @LKUP_TYPE ELSE LOOKUPTYPE END
								WHERE LOOKUPMAINID = @PKC1
							IF @@ROWCOUNT = 0
								IF @@MICROSOFTVERSION>0X07320000
									BEGIN
										IF EXISTS (SELECT * FROM SYS.ALL_PARAMETERS WHERE OBJECT_ID = OBJECT_ID('SP_MSREPLRAISERROR') AND [NAME] = '@PARAM3')
										BEGIN
				
											SET @PRIMARYKEY_TEXT = @PRIMARYKEY_TEXT + '[SYS_USR_ID] = ' + CONVERT(NVARCHAR(100),@PKC1,1)
											EXEC SP_MSREPLRAISERROR @ERRORID=20598, @PARAM1=N'[DBO].[UMS_SYS_USR]', @PARAM2=@PRIMARYKEY_TEXT, @PARAM3=13233 
										END
										ELSE
											EXEC SP_MSREPLRAISERROR @ERRORID=20598
									END
					END
			END TRY
			BEGIN CATCH
					SELECT
					ERROR_NUMBER() AS ERRORNUMBER,
					ERROR_STATE() AS ERRORSTATE,
					ERROR_SEVERITY() AS ERRORSEVERITY,
					ERROR_PROCEDURE() AS ERRORPROCEDURE,
					ERROR_LINE() AS ERRORLINE,
					ERROR_MESSAGE() AS ERRORMESSAGE;
			END CATCH;
		END 
END 
GO


